from .models_mae_translate_template import mae_vit_base_patch16, mae_vit_large_patch16, mae_vit_huge_patch14, mae_vit_small_patch16
from .models_mae import mae_vit_base_patch16 as mae_vit_base_patch16_ori
